# Generated by Django 4.2.9 on 2026-06-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MallOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('point_price', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', '已完成'), ('cancelled', '已取消'), ('delivered', '已发货')], default='completed', max_length=16)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=64)),
                ('coupon_expire_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_no', models.CharField(blank=True, default='', max_length=64)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MallProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('coupon', '优惠券'), ('perk', '权益'), ('merch', '周边实物'), ('ticket', '赠票')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('point_price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('limit_per_member', models.IntegerField(default=0)),
                ('coupon_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('coupon_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coupon_valid_days', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='', max_length=16)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('growth_value', models.IntegerField(default=0)),
                ('period_growth', models.IntegerField(default=0)),
                ('points_balance', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_points_spent', models.IntegerField(default=0)),
                ('free_refund_used', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_attended', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('level', models.IntegerField(unique=True)),
                ('min_growth', models.IntegerField(default=0)),
                ('max_growth', models.IntegerField(default=0)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('priority_hours', models.IntegerField(default=0)),
                ('priority_quota', models.IntegerField(default=0)),
                ('free_refund_count', models.IntegerField(default=0)),
                ('birthday_gift', models.CharField(blank=True, default='', max_length=255)),
                ('dedicated_support', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member_levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(default='', max_length=64)),
                ('start_at', models.DateTimeField()),
                ('total_seats', models.IntegerField(default=0)),
                ('sold_seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority_start_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='PointBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_ref', models.CharField(blank=True, default='', max_length=64)),
                ('total_points', models.IntegerField(default=0)),
                ('remaining_points', models.IntegerField(default=0)),
                ('earned_at', models.DateTimeField()),
                ('expire_at', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_batches', to='tickets.member')),
            ],
            options={
                'db_table': 'point_batches',
                'ordering': ['expire_at'],
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', '消费购票'), ('review', '演出评价'), ('checkin', '签到'), ('activity', '活动奖励'), ('birthday', '生日礼'), ('refund_return', '退票返还'), ('admin', '管理员调整')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0)),
                ('per_yuan', models.IntegerField(default=0)),
                ('expire_days', models.IntegerField(default=365)),
                ('daily_limit', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'point_rules',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('troupe', models.CharField(blank=True, default='', max_length=128)),
                ('genre', models.CharField(choices=[('concert', '演唱会'), ('drama', '话剧'), ('musical', '音乐剧'), ('opera', '戏曲'), ('other', '其他')], default='concert', max_length=16)),
                ('status', models.CharField(choices=[('on_sale', '售票中'), ('upcoming', '待开票'), ('ended', '已结束')], default='upcoming', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('point_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_used', models.IntegerField(default=0)),
                ('channel', models.CharField(choices=[('normal', '普通购买'), ('priority', '优先购')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退票')], default='paid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tickets.member')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.performance')),
            ],
            options={
                'db_table': 'ticket_orders',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', '获取'), ('spend', '消耗'), ('expire', '过期'), ('refund', '退还')], max_length=16)),
                ('points', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('source_ref', models.CharField(blank=True, default='', max_length=64)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tickets.pointbatch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='tickets.member')),
            ],
            options={
                'db_table': 'point_transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePriorityQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quota', models.IntegerField(default=0)),
                ('used_quota', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_quotas', to='tickets.memberlevel')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_quotas', to='tickets.performance')),
            ],
            options={
                'db_table': 'performance_priority_quotas',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.show'),
        ),
        migrations.CreateModel(
            name='MemberCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=16)),
                ('expire_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mall_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.mallorder')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tickets.member')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.mallproduct')),
                ('used_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketorder')),
            ],
            options={
                'db_table': 'member_coupons',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='tickets.memberlevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mallproduct',
            name='min_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.memberlevel'),
        ),
        migrations.AddField(
            model_name='mallorder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_orders', to='tickets.member'),
        ),
        migrations.AddField(
            model_name='mallorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tickets.mallproduct'),
        ),
        migrations.CreateModel(
            name='LevelChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('upgrade', '升级'), ('downgrade', '降级'), ('initial', '初始')], max_length=16)),
                ('growth_before', models.IntegerField(default=0)),
                ('growth_after', models.IntegerField(default=0)),
                ('notified', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.memberlevel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_changes', to='tickets.member')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.memberlevel')),
            ],
            options={
                'db_table': 'level_change_logs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', '消费购票'), ('attend', '观演完成'), ('activity', '活动奖励'), ('admin', '管理员调整')], max_length=32)),
                ('growth', models.IntegerField(default=0)),
                ('source_ref', models.CharField(blank=True, default='', max_length=64)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='tickets.member')),
            ],
            options={
                'db_table': 'growth_records',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pointbatch',
            index=models.Index(fields=['member', 'expire_at'], name='point_batch_member__5c6fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='pointbatch',
            index=models.Index(fields=['expire_at', 'expired'], name='point_batch_expire__de808f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancepriorityquota',
            unique_together={('performance', 'level')},
        ),
    ]
